[env]
_.file = ".envrc"

TG_STRICT_CONTROL = "root-terragrunt-hcl"

[tools]
terraform = "1.11.4"
terragrunt = "0.77.17"
terraform-docs = "0.20.0"
pre-commit = "4.2.0"
sops = "3.10.2"
typos = "1.31.1"
tflint = "0.56.0"
trivy = "0.61.0"

[hooks]
postinstall = "pre-commit install"

[tasks.clean]
description = "Delete terragrunt cache directories"
run = 'find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;'
alias = "cl"
