# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terragrunt-test-example-state"
    encrypt = true
    key     = "example/data/terraform.tfstate"
    region  = "ap-northeast-1"
  }
}
