# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-northeast-1"
  default_tags {
    tags = {
      Project     = "terragrunt-test"
      Environment = "example"
      ManagedBy   = "Terraform"
    }
  }
}

provider "aws" {
  alias  = "virginia"
  region = "us-east-1"

  default_tags {
    tags = {
      Project     = "terragrunt-test"
      Environment = "example"
      ManagedBy   = "Terraform"
    }
  }
}

provider "awscc" {
  region = "ap-northeast-1"
}
