# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = "1.11.4"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.94.1"
    }
    awscc = {
      source  = "hashicorp/awscc"
      version = "1.36.0"
    }
  }
}
